context.modules = [
    { name = libpipewire-module-filter-chain
        args = {
            node.description = "Hoehenschutz"
            media.name       = "Hoehenschutz"
            filter.graph = {
                nodes = [
                    {
                        type  = builtin
                        name  = treble_shelf
                        label = bq_highshelf
                        control = { "Freq" = 8000.0 "Q" = 0.7 "Gain" = -4.0 }
                    }
                ]
            }
            audio.channels = 2
            audio.position = [ FL FR ]
            capture.props = {
                node.name   = "hearing_filter_in"
                media.class = Audio/Sink
                filter.smart = true
                filter.smart.name = hearing-filter
            }
            playback.props = {
                node.name   = "hearing_filter_out"
                node.passive = true
                stream.dont-remix = true
            }
        }
    }
]
